all:
  children:
    manager:
      hosts:
        192.168.1.12:
         ansible_user: manager
         ansible_become_pass: iheb
         ansible_ssh_pass: iheb
        
    worker:
      hosts:
        worker1.duckdns.org:
         ansible_user: worker1
         ansible_port: 2221
        worker2.duckdns.org:
         ansible_user: worker2
         ansible_port: 2222
  vars:
    ansible_ssh_private_key_file: "/home/manager/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_become_pass: iheb
