all:
  children:
    manager:
      hosts:
        192.168.1.16:
         ansible_user: manager
         ansible_become_pass: iheb
         ansible_ssh_pass: iheb
        
    worker:
      hosts:
        192.168.1.14:
         ansible_user: worker1
        192.168.1.11:
         ansible_user: worker2
  vars:
    ansible_ssh_private_key_file: "/home/manager/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_become_pass: iheb
