version: '3.9'

services:
  myapp:
    image: houbalinko/flaskapp2:0.1.66
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
    ports:
      - '5000:5000'
    labels:
      visualizer.autoscale.min: '1'
      visualizer.autoscale.max: '5'
      visualizer.autoscale.up.cpu: '0.2'
      visualizer.autoscale.down.cpu: '0.1'
      visualizer.autoupdate: 'true'
      # Traefik labels
      traefik.enable: 'true'
      traefik.http.routers.myapp.rule: Host(`app.localhost`)  # Set the domain rule
      traefik.http.routers.myapp.entrypoints: web
      traefik.http.services.myapp.loadbalancer.server.port: 5000
      # Other Traefik-related labels

networks:
  traefik-public:
    external: true

